//
//  KRResponse.h
//  Kraken
//
//  Created by Ovidiu on 06/03/15.
//  Copyright (c) 2015 Appscend. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface KRResponse : NSObject

/**
 *  A `NSDictionary` containing the decoded JSON (if successful)
 */
@property (nonatomic, strong) NSDictionary *dict;

/**
 *  The original `NSData` object from which the JSON was generated (if available)
 */
@property (nonatomic, strong) NSData *data;

/**
 *  The HTTP response status
 */
@property (nonatomic) NSInteger status;

/**
 *  The error generated by the request, if any
 */
@property (nonatomic, strong) NSError *error;

/**
 *  Init with a dictionary
 *
 *  @param dict   The dictionary
 *  @param status The HTTP request status
 *
 *  @return A new instance containing the given dictionary and status
 */
- (id) initWithDictionary:(NSDictionary *)dict andStatus:(NSInteger)status;

/**
 *  Init with data
 *
 *  @param data   The data returned by the request
 *  @param status The HTTP request status
 *
 *  @return A new instance containing the given data and, if valid, a dictionary with the decoded data
 */
- (id) initWithData:(NSData *)data andStatus:(NSInteger)status;

/**
 *  Init with an error
 *
 *  @param error The error returned by the request
 *
 *  @return A new instance containing the error given by the request
 */
- (id) initWithError:(NSError *)error;

/**
 *  Returns a `NSData` representation of the current JSON
 *
 *  @return A `NSData` representation of the current JSON
 */
- (NSData *) asData;

/**
 *  Returns the JSON as string
 *
 *  @return A `NSString` representation of the current JSON
 */
- (NSString *) asString;

@end
